export const ordemDosBotoes = [
    {"id": 0,     "valor": "CE",          "estiloDoBotao": "2",    "tipoDoBotao": "operacao"},
    {"id": 1,     "valor": "C",           "estiloDoBotao": "1",    "tipoDoBotao": "operacao"},
    {"id": 2,     "valor": "percentual",  "estiloDoBotao": "1",    "tipoDoBotao": "operacao"},
    {"id": 3,     "valor": "dividir",     "estiloDoBotao": "3",    "tipoDoBotao": "operacao"},
    {"id": 4,     "valor": "7",           "estiloDoBotao": "1",    "tipoDoBotao": "numerico"},
    {"id": 5,     "valor": "8",           "estiloDoBotao": "1",    "tipoDoBotao": "numerico"},
    {"id": 6,     "valor": "9",           "estiloDoBotao": "1",    "tipoDoBotao": "numerico"},
    {"id": 7,     "valor": "multiplicar", "estiloDoBotao": "3",    "tipoDoBotao": "operacao"},
    {"id": 8,     "valor": "4",           "estiloDoBotao": "1",    "tipoDoBotao": "numerico"},
    {"id": 9,     "valor": "5",           "estiloDoBotao": "1",    "tipoDoBotao": "numerico"},
    {"id": 10,    "valor": "6",           "estiloDoBotao": "1",    "tipoDoBotao": "numerico"},
    {"id": 11,    "valor": "subtrair",    "estiloDoBotao": "3",    "tipoDoBotao": "operacao"},
    {"id": 12,    "valor": "1",           "estiloDoBotao": "1",    "tipoDoBotao": "numerico"},
    {"id": 13,    "valor": "2",           "estiloDoBotao": "1",    "tipoDoBotao": "numerico"},
    {"id": 14,    "valor": "3",           "estiloDoBotao": "1",    "tipoDoBotao": "numerico"},
    {"id": 15,    "valor": "somar",       "estiloDoBotao": "3",    "tipoDoBotao": "operacao"},
    {"id": 16,    "valor": "maisMenos",   "estiloDoBotao": "1",    "tipoDoBotao": "operacao"},
    {"id": 17,    "valor": "0",           "estiloDoBotao": "1",    "tipoDoBotao": "numerico"},
    {"id": 18,    "valor": ",",           "estiloDoBotao": "1",    "tipoDoBotao": "."},
    {"id": 19,    "valor": "igual",       "estiloDoBotao": "4",    "tipoDoBotao": "igual"}
];